name: Use Secrets in Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Print a Secret
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          echo "The API key is: $API_KEY"
